### ISSUE TITLE
errors if the shp file contains points as geometries

### ISSUE THREAD

**Issue by cesandoval** [open-reblock/localco.de#23]
![screen shot 2015-07-09 at 4 57 31 pm](https://cloud.githubusercontent.com/assets/1952351/8609569/d963db7e-265b-11e5-9ccb-aa9252dc40d1.png)

**Comment by panthersuper** [comment]
can you upload the shp file that cause the error?

**Comment by panthersuper** [comment]
The error is fixed and pushed to master.
