### ISSUE TITLE
something in backend causing repeat UI elements to render?

### ISSUE THREAD

**Issue by danrademacher** [open-reblock/localco.de#28]
We've noticed that running a file like this: http://openreblock.berkeley.edu/reblock/compute/danrademacher_cape-town-plan_cape-town-where-i-live_2/

Creates a page like this:
![image](https://cloud.githubusercontent.com/assets/1423200/9774327/92e6c734-56fc-11e5-8fbb-eb7a1ec60cf8.png)

Anyone have an idea what's causing all these repeated UI elements?

**Comment by panthersuper** [comment]
Can't open that url maybe because of user limitation...
I'm not able to get it tested... It seems to be a front end error? 
If possible you can test it by printing the data query process(in the html) and see what cause the problem

**Comment by panthersuper** [comment]
One possibility is more than one geo data is saved in the database and all queried in this page, and they overlap on the map, while causing multiple sliders for each...

**Comment by danrademacher** [comment]
Good thought. This Cape Town example has 61 steps, so it's clearly not loading one for every step (where each step has associated geo data). Looks like if I refresh the page, sometimes it renders single items as expected, other times it shows multiple (once it rendered 2 and then in screenshot above, 7).

**Comment by panthersuper** [comment]
If that happens to the same page(same url), that seem to be a front end issue.

**Comment by ericsoco** [comment]
I haven't been able to repro this, but I have seen something similar on other pages (and fixed it). It was due to django templates being included twice. Not sure if that's happening here or not. Closing as can't repro but can reopen if it's still an issue.
