### ISSUE TITLE
Style header to design

### ISSUE THREAD

**Issue by danrademacher** [open-reblock/localco.de#29]
currently:
![image](https://cloud.githubusercontent.com/assets/1423200/9855230/d7dc0ec6-5ac1-11e5-9358-9ff8f2d8286a.png)

As designed:
![image](https://cloud.githubusercontent.com/assets/1423200/9855224/ce610a18-5ac1-11e5-8d37-6d7e08e2db69.png)

**Comment by ericsoco** [comment]
![screen shot 2015-09-28 at 1 22 37 pm](https://cloud.githubusercontent.com/assets/1127259/10147661/2541dd8a-65e4-11e5-96ad-f91a21941003.png)
