### ISSUE TITLE
nested routes for short path computations

### ISSUE THREAD

**Issue by cesandoval** [open-reblock/localco.de#3]
- [x] Create views to construct urls based on place, user, id, step, and date [Example 1](http://azizmb.in/pattern-for-nested-resources-in-django.html), [Example 2](https://wellfire.co/blog/fast-and-beautiful-urls-with-django/)
- [x] Create model to "slugify" place names [Example 1](https://docs.djangoproject.com/en/1.8/ref/utils/#module-django.utils.text)
- [x] Modify urls.py to render nested routes

**Comment by cesandoval** [comment]
I think the urls are up and running. Should I close this?

**Comment by panthersuper** [comment]
sure!
