### ISSUE TITLE
Style upload reblock page

### ISSUE THREAD

**Issue by danrademacher** [open-reblock/localco.de#31]
Currently:
![image](https://cloud.githubusercontent.com/assets/1423200/9855250/f677fa52-5ac1-11e5-99c6-a4975767489b.png)

As designed:
![open_reblock_frontend_2upload 1](https://cloud.githubusercontent.com/assets/1423200/9855253/fa88cc0c-5ac1-11e5-8335-33880e228423.png)

**Comment by ericsoco** [comment]
The screenshot here is for the upload "review" page (/reblock/review/), not the upload page (/reblock/upload/). I'll apply some minimal styling to the upload page as well. Review page is done:

![screen shot 2015-10-01 at 11 45 47 am](https://cloud.githubusercontent.com/assets/1127259/10230468/07879960-6832-11e5-9c5f-d53467085bc8.png)

**Comment by ericsoco** [comment]
![screen shot 2015-10-01 at 1 19 38 pm](https://cloud.githubusercontent.com/assets/1127259/10232719/2a68b9f2-683f-11e5-9ec5-f0d588f48162.png)
