### ISSUE TITLE
Style login page

### ISSUE THREAD

**Issue by danrademacher** [open-reblock/localco.de#32]
Currently:
![image](https://cloud.githubusercontent.com/assets/1423200/9855273/1cf95e3c-5ac2-11e5-9ce4-2864ce9bbf62.png)

As designed:
![open_reblock_frontend_4log in](https://cloud.githubusercontent.com/assets/1423200/9855275/229178d4-5ac2-11e5-9d4f-b555caa591ce.png)

**Comment by ericsoco** [comment]
![screen shot 2015-09-28 at 1 22 17 pm](https://cloud.githubusercontent.com/assets/1127259/10147652/16fb4c02-65e4-11e5-9eed-c1566d4c7754.png)
