### ISSUE TITLE
Style lost password page

### ISSUE THREAD

**Issue by danrademacher** [open-reblock/localco.de#33]
Currently:
![image](https://cloud.githubusercontent.com/assets/1423200/9855286/392c2404-5ac2-11e5-90e8-21f5ed4c4f8c.png)

As designed:
![open_reblock_frontend_5password reset](https://cloud.githubusercontent.com/assets/1423200/9855279/2de7ba90-5ac2-11e5-8dfd-e8e8392fe7d5.png)

**Comment by ericsoco** [comment]
![screen shot 2015-09-28 at 1 22 03 pm](https://cloud.githubusercontent.com/assets/1127259/10147644/0dbf4224-65e4-11e5-82a1-78aaddca85ee.png)
