### ISSUE TITLE
Style profile page

### ISSUE THREAD

**Issue by danrademacher** [open-reblock/localco.de#34]
Currently:
![image](https://cloud.githubusercontent.com/assets/1423200/9855300/52572604-5ac2-11e5-85c8-87997e27cd92.png)

As designed:
![open_reblock_frontend_7profile](https://cloud.githubusercontent.com/assets/1423200/9855304/59e7ea34-5ac2-11e5-990a-be0ffe7e8ead.png)

**Comment by ericsoco** [comment]
I assume "currently" and "as designed" are swapped here?

**Comment by danrademacher** [comment]
Yep, now fixed

**Comment by ericsoco** [comment]
![screen shot 2015-10-01 at 5 57 21 pm](https://cloud.githubusercontent.com/assets/1127259/10237407/ea373828-6865-11e5-9fbb-4f08e5f71933.png)
