### ISSUE TITLE
/reblock/review displays UI twice

### ISSUE THREAD

**Issue by ericsoco** [open-reblock/localco.de#44]
After uploading a file, the page that displays (the upload review page) shows some UI elements twice. It appears that a django template is inserted inside of itself, or....something. I think I caused this when editing the HTML/CSS. Labeling as Front-end pending further investigation.

**Comment by ericsoco** [comment]
![screen shot 2015-10-01 at 3 10 12 pm](https://cloud.githubusercontent.com/assets/1127259/10235185/1dcf99ee-684f-11e5-983c-898ec950fc85.png)

**Comment by ericsoco** [comment]
The django templates were a mess. I straightened them out a bit.

**Comment by joehand** [comment]
Thanks! :+1:
