### ISSUE TITLE
runtopology() got an unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by cesandoval** [open-reblock/localco.de#9]
Seems like we are running into the same issue on the server install. Celery wont recognize the argument for the runtopology() task.

![image](https://cloud.githubusercontent.com/assets/1952351/8505024/136db9c2-2191-11e5-81ee-e3664cfd5dab.png)

**Comment by panthersuper** [comment]
This error is because the runtopology function in tasks is changed, try to
update tasks and should be solved

**Comment by cesandoval** [comment]
great, updated tasks and syncdb. I'll close it
